# Generated by Django 3.2.3 on 2021-07-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20210717_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('phone', models.IntegerField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
                ('price', models.IntegerField(max_length=1000)),
            ],
        ),
    ]
