# Generated by Django 3.2.3 on 2021-07-18 15:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20210718_2107'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2021, 7, 18, 15, 40, 19, 163124, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
