# Generated by Django 3.2.3 on 2021-07-22 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20210718_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
