# Generated by Django 3.2.3 on 2021-07-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price',
        ),
    ]
