# Generated by Django 3.2.3 on 2021-07-29 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20210729_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='dates',
        ),
        migrations.RemoveField(
            model_name='order',
            name='timing',
        ),
    ]
