# Generated by Django 3.2.3 on 2021-07-29 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20210729_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timing',
            field=models.CharField(default='29/7/2021 12:30', max_length=1000),
            preserve_default=False,
        ),
    ]
