# Generated by Django 3.2.3 on 2021-09-06 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_order_timing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='s_price',
            field=models.CharField(default='', max_length=100),
        ),
    ]
