# Generated by Django 3.2.3 on 2021-09-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_order_f_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='5 Kg Order, No special instructions', max_length=1000),
            preserve_default=False,
        ),
    ]
