# Generated by Django 3.2.3 on 2021-09-13 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_order_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='comment',
        ),
    ]
