# Generated by Django 3.2.3 on 2021-09-13 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='s_ac',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='services',
            name='s_dc',
            field=models.CharField(default='', max_length=100),
        ),
    ]
