# Generated by Django 3.2.3 on 2021-09-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20210913_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='s_ac',
            field=models.CharField(default='60', max_length=100),
        ),
        migrations.AlterField(
            model_name='services',
            name='s_dc',
            field=models.CharField(default='10', max_length=100),
        ),
    ]
