# Generated by Django 3.2.3 on 2021-09-16 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20210913_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='dry_clean_services',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('s_name', models.CharField(default='', max_length=100)),
                ('s_price', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
