# Generated by Django 3.2.3 on 2021-09-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_dry_clean_services'),
    ]

    operations = [
        migrations.AddField(
            model_name='dry_clean_services',
            name='s_parent',
            field=models.CharField(default='', max_length=100),
        ),
    ]
