# Generated by Django 3.2.3 on 2021-09-17 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_dry_clean_services_s_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.CharField(default='17/09/2021', max_length=1000),
            preserve_default=False,
        ),
    ]
