# Generated by Django 3.2.3 on 2021-09-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='date',
        ),
    ]
