# Generated by Django 3.2.3 on 2021-09-18 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_dry_clean_services_s_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='dry_clean_services',
            name='s_parent',
            field=models.CharField(default='Ladies', max_length=100),
        ),
    ]
