# Generated by Django 3.2.3 on 2021-09-19 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_alter_dry_clean_services_s_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='deleted_orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('original_id', models.CharField(max_length=1000)),
                ('name', models.CharField(max_length=1000)),
                ('phone', models.IntegerField()),
                ('order_name', models.CharField(max_length=1000)),
                ('address', models.CharField(max_length=1000)),
            ],
        ),
    ]
