# Generated by Django 2.1.15 on 2021-11-22 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_order_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='pr',
            field=models.CharField(default='true', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='weight',
            field=models.CharField(default='Not Specified', max_length=1000),
        ),
    ]
