# Generated by Django 3.2.3 on 2022-02-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0034_auto_20211228_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_review',
            field=models.CharField(default='No review', max_length=1000),
        ),
        migrations.AddField(
            model_name='order',
            name='laundry_review',
            field=models.CharField(default='No review', max_length=1000),
        ),
    ]
