# Generated by Django 3.2.3 on 2022-02-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_alter_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refer_code',
            field=models.CharField(default='-', max_length=1000),
        ),
    ]
